/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProblemId = IDL.Nat;
export const ThreadId = IDL.Nat;
export const Dataset = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'recordCount' : IDL.Nat,
});
export const Problem = IDL.Record({
  'id' : ProblemId,
  'title' : IDL.Text,
  'submittedBy' : IDL.Text,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
  'threadId' : ThreadId,
});
export const User = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
});
export const IdeaId = IDL.Nat;
export const Idea = IDL.Record({
  'id' : IdeaId,
  'title' : IDL.Text,
  'feasibilityScore' : IDL.Nat,
  'description' : IDL.Text,
  'problemId' : ProblemId,
  'category' : IDL.Text,
});
export const ThreadView = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'problemId' : ProblemId,
});

export const idlService = IDL.Service({
  'addDataset' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Int],
      [],
      [],
    ),
  'createThread' : IDL.Func([IDL.Text, ProblemId], [ThreadId], []),
  'getDatasetById' : IDL.Func([IDL.Nat], [Dataset], ['query']),
  'getProblemById' : IDL.Func([ProblemId], [Problem], ['query']),
  'getThreadMessages' : IDL.Func([ThreadId], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Text], [User], ['query']),
  'listDatasets' : IDL.Func([], [IDL.Vec(Dataset)], ['query']),
  'listIdeasByProblemId' : IDL.Func([ProblemId], [IDL.Vec(Idea)], ['query']),
  'listProblems' : IDL.Func([], [IDL.Vec(Problem)], ['query']),
  'listThreads' : IDL.Func([], [IDL.Vec(ThreadView)], ['query']),
  'postMessage' : IDL.Func([ThreadId, IDL.Text, IDL.Text], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'storeIdea' : IDL.Func(
      [ProblemId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IdeaId],
      [],
    ),
  'submitProblem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ProblemId], []),
  'validateLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProblemId = IDL.Nat;
  const ThreadId = IDL.Nat;
  const Dataset = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'recordCount' : IDL.Nat,
  });
  const Problem = IDL.Record({
    'id' : ProblemId,
    'title' : IDL.Text,
    'submittedBy' : IDL.Text,
    'description' : IDL.Text,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
    'threadId' : ThreadId,
  });
  const User = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  const IdeaId = IDL.Nat;
  const Idea = IDL.Record({
    'id' : IdeaId,
    'title' : IDL.Text,
    'feasibilityScore' : IDL.Nat,
    'description' : IDL.Text,
    'problemId' : ProblemId,
    'category' : IDL.Text,
  });
  const ThreadView = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'problemId' : ProblemId,
  });
  
  return IDL.Service({
    'addDataset' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Int],
        [],
        [],
      ),
    'createThread' : IDL.Func([IDL.Text, ProblemId], [ThreadId], []),
    'getDatasetById' : IDL.Func([IDL.Nat], [Dataset], ['query']),
    'getProblemById' : IDL.Func([ProblemId], [Problem], ['query']),
    'getThreadMessages' : IDL.Func([ThreadId], [IDL.Vec(Message)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Text], [User], ['query']),
    'listDatasets' : IDL.Func([], [IDL.Vec(Dataset)], ['query']),
    'listIdeasByProblemId' : IDL.Func([ProblemId], [IDL.Vec(Idea)], ['query']),
    'listProblems' : IDL.Func([], [IDL.Vec(Problem)], ['query']),
    'listThreads' : IDL.Func([], [IDL.Vec(ThreadView)], ['query']),
    'postMessage' : IDL.Func([ThreadId, IDL.Text, IDL.Text], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'storeIdea' : IDL.Func(
        [ProblemId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IdeaId],
        [],
      ),
    'submitProblem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ProblemId], []),
    'validateLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };