/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Dataset {
  'id' : bigint,
  'name' : string,
  'lastUpdated' : bigint,
  'description' : string,
  'category' : string,
  'recordCount' : bigint,
}
export interface Idea {
  'id' : IdeaId,
  'title' : string,
  'feasibilityScore' : bigint,
  'description' : string,
  'problemId' : ProblemId,
  'category' : string,
}
export type IdeaId = bigint;
export interface Message {
  'id' : bigint,
  'content' : string,
  'author' : string,
  'timestamp' : Time,
  'threadId' : ThreadId,
}
export interface Problem {
  'id' : ProblemId,
  'title' : string,
  'submittedBy' : string,
  'description' : string,
}
export type ProblemId = bigint;
export type ThreadId = bigint;
export interface ThreadView {
  'id' : bigint,
  'title' : string,
  'messages' : Array<Message>,
  'problemId' : ProblemId,
}
export type Time = bigint;
export interface User {
  'name' : string,
  'email' : string,
  'passwordHash' : string,
}
export interface _SERVICE {
  'addDataset' : ActorMethod<
    [bigint, string, string, string, bigint, bigint],
    undefined
  >,
  'createThread' : ActorMethod<[string, ProblemId], ThreadId>,
  'getDatasetById' : ActorMethod<[bigint], Dataset>,
  'getProblemById' : ActorMethod<[ProblemId], Problem>,
  'getThreadMessages' : ActorMethod<[ThreadId], Array<Message>>,
  'getUserProfile' : ActorMethod<[string], User>,
  'listDatasets' : ActorMethod<[], Array<Dataset>>,
  'listIdeasByProblemId' : ActorMethod<[ProblemId], Array<Idea>>,
  'listProblems' : ActorMethod<[], Array<Problem>>,
  'listThreads' : ActorMethod<[], Array<ThreadView>>,
  'postMessage' : ActorMethod<[ThreadId, string, string], undefined>,
  'registerUser' : ActorMethod<[string, string, string], undefined>,
  'storeIdea' : ActorMethod<
    [ProblemId, string, string, bigint, string],
    IdeaId
  >,
  'submitProblem' : ActorMethod<[string, string, string], ProblemId>,
  'validateLogin' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];