/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ThreadId = bigint;
export type IdeaId = bigint;
export type Time = bigint;
export interface Dataset {
    id: bigint;
    name: string;
    lastUpdated: bigint;
    description: string;
    category: string;
    recordCount: bigint;
}
export interface User {
    name: string;
    email: string;
    passwordHash: string;
}
export interface Message {
    id: bigint;
    content: string;
    author: string;
    timestamp: Time;
    threadId: ThreadId;
}
export interface Problem {
    id: ProblemId;
    title: string;
    submittedBy: string;
    description: string;
}
export interface ThreadView {
    id: bigint;
    title: string;
    messages: Array<Message>;
    problemId: ProblemId;
}
export type ProblemId = bigint;
export interface Idea {
    id: IdeaId;
    title: string;
    feasibilityScore: bigint;
    description: string;
    problemId: ProblemId;
    category: string;
}
export interface backendInterface {
    addDataset(id: bigint, name: string, description: string, category: string, recordCount: bigint, lastUpdated: bigint): Promise<void>;
    createThread(title: string, problemId: ProblemId): Promise<ThreadId>;
    getDatasetById(id: bigint): Promise<Dataset>;
    getProblemById(id: ProblemId): Promise<Problem>;
    getThreadMessages(threadId: ThreadId): Promise<Array<Message>>;
    getUserProfile(email: string): Promise<User>;
    listDatasets(): Promise<Array<Dataset>>;
    listIdeasByProblemId(problemId: ProblemId): Promise<Array<Idea>>;
    listProblems(): Promise<Array<Problem>>;
    listThreads(): Promise<Array<ThreadView>>;
    postMessage(threadId: ThreadId, content: string, author: string): Promise<void>;
    registerUser(name: string, email: string, passwordHash: string): Promise<void>;
    storeIdea(problemId: ProblemId, title: string, description: string, feasibilityScore: bigint, category: string): Promise<IdeaId>;
    submitProblem(title: string, description: string, submittedBy: string): Promise<ProblemId>;
    validateLogin(email: string, passwordHash: string): Promise<boolean>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDataset(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDataset(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDataset(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createThread(arg0: string, arg1: ProblemId): Promise<ThreadId> {
        if (this.processError) {
            try {
                const result = await this.actor.createThread(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createThread(arg0, arg1);
            return result;
        }
    }
    async getDatasetById(arg0: bigint): Promise<Dataset> {
        if (this.processError) {
            try {
                const result = await this.actor.getDatasetById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDatasetById(arg0);
            return result;
        }
    }
    async getProblemById(arg0: ProblemId): Promise<Problem> {
        if (this.processError) {
            try {
                const result = await this.actor.getProblemById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProblemById(arg0);
            return result;
        }
    }
    async getThreadMessages(arg0: ThreadId): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getThreadMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThreadMessages(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return result;
        }
    }
    async listDatasets(): Promise<Array<Dataset>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDatasets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDatasets();
            return result;
        }
    }
    async listIdeasByProblemId(arg0: ProblemId): Promise<Array<Idea>> {
        if (this.processError) {
            try {
                const result = await this.actor.listIdeasByProblemId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listIdeasByProblemId(arg0);
            return result;
        }
    }
    async listProblems(): Promise<Array<Problem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProblems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProblems();
            return result;
        }
    }
    async listThreads(): Promise<Array<ThreadView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listThreads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listThreads();
            return result;
        }
    }
    async postMessage(arg0: ThreadId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2);
            return result;
        }
    }
    async storeIdea(arg0: ProblemId, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<IdeaId> {
        if (this.processError) {
            try {
                const result = await this.actor.storeIdea(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeIdea(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitProblem(arg0: string, arg1: string, arg2: string): Promise<ProblemId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitProblem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitProblem(arg0, arg1, arg2);
            return result;
        }
    }
    async validateLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateLogin(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
